### ISSUE TITLE
3.0 b2 Spelling

### ISSUE THREAD

**Issue by ChrisChiera** [Fitoussi/geo-my-wp#56]
Love the beautiful new backend design. Just a few issues I noticed:

Search Results Tab
- "Check this checkbox to disply" should be "Check this checkbox to display" 
- Under image section, "show more..." appears twice.

On Extensions page says "Prmeium" on top, should be, "Premium".

Form Usage
- "shortocde" should be "shortcode"

Post Types
- "Deafult" should be "Default"

**Comment by Fitoussi** [comment]
Thank you. all fixed.

There is so much text in the plugin. I am pretty sure there are many more misspelled words and grammar issues :). Please let me know if you find any others.

**Comment by ChrisChiera** [comment]
Awesome, thanks!
