### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by ChrisChiera** [Fitoussi/geo-my-wp#61]
Great plugin! Noticed a few spelling errors I'd thought I'd share with you. Haven't upgraded to the latest version so not sure if these have already been fixed.

Tools > System Info
Says "Downlaod" should say "Download"

GEO My WP Extensions > Tab
Says "Prmeium" should say "Premium"

Posts Locator > Page Load Results > Visitor's Current Location
Says "Ingnored" should say "ignored"

Posts Locator > Search Form > Address Field
Says "dynaimcally" should say "dynamically"

Posts Locator > Search Form > Locator Button
Says "retrive" should say "retrieve"

Posts Locator > Form Submission > Display Map
Says "completly" should say "completely"

Posts Locator > Form Usage > Last Section
Says "shortocde" should say "shortcode"

**Comment by neilmcg3000** [comment]
Posts Locator > Form Usage > Last Section
Says "shortocde" should say "shortcake"

Surely should be “shortcode”

**Comment by ChrisChiera** [comment]
Sorry yes. My Mac kept trying to auto correct non stop which made this post hard to type =).

**Comment by Fitoussi** [comment]
Hi @ChrisChiera,

I apologize for the delayed reply. And thank you for the above. 

A few of the spelling errors you mentioned were already addressed in a previous version. The rest I have just fixed and it will be available in the next release.

Thanks,
