### ISSUE TITLE
Fatal error when using GMW Widget with latest update

### ISSUE THREAD

**Issue by GhosttownLLC** [Fitoussi/geo-my-wp#67]
When adding a widget of the GEO My WP, I get the following error:

`2019/11/30 18:15:09 [error] 12267#12267: *1603411 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'GMW_Current_Location' not found in /var/www/vhosts/floordetective.ng/wp-content/plugins/geo-my-wp/plugins/current-location/includes/class-gmw-current-location-widget.php:203`

**Comment by barrychapman** [comment]
cancelling all subscriptions

**Comment by Fitoussi** [comment]
@barrychapman,

This issue has been fixed a while ago.

Are you still experiencing it?
