### ISSUE TITLE
Age range bug

### ISSUE THREAD

**Issue by ivok2002** [Fitoussi/GEO-my-WP#7]
Hi,

Thanks for the nice plugin. It is really helpful.
I found a little bug concerning the age range search.

File: gmw-fl-template-functions.php
Original Line: echo 	'<input size="3" type="text" name="'.$fname.'-max" id="'.$fid.'_max" class="'.$fclass.'-max" value="'.$max.'" placeholder="'.__( 'Max', 'GMW' ).'" />';
Corrected Line: echo 	'<input size="3" type="text" name="'.$fname.'_max" id="'.$fid.'_max" class="'.$fclass.'_max" value="'.$max.'" placeholder="'.__( 'Max', 'GMW' ).'" />';

The problem is that there is '-' instead of '_', and the max value is never be taken.
Please add this minor fix in the original version.
Thanks in advance.

Ivaylo

**Comment by Fitoussi** [comment]
Thank you. Fixed and new release uploaded
