### ISSUE TITLE
add_hidden_status_field() js error

### ISSUE THREAD

**Issue by r-baudot** [Fitoussi/geo-my-wp#71]
There is a console issue on the add_hidden_status_field function in class-gmw-posts-locator-screens.php
![Capture d’écran 2020-11-02 à 14 35 42](https://user-images.githubusercontent.com/31986970/97874052-bc452200-1d18-11eb-9b6d-7a9a7c89fa9b.png)

PLease replace :
`$pods_enabled = class_exists( 'PodsAdmin' ) ? true : false;`
by
`$pods_enabled = class_exists( 'PodsAdmin' ) ? "true" : "false";`

**Comment by Fitoussi** [comment]
Thank you @r-baudot for pointing it out.

Working on a fix now.
